---
title: "{{< fa seedling >}} Environmental Quality MSc Program"
echo: false
# jupyter: python3
section-divs: false
---


## General information

* The Faculty of Agriculture's regulations for Master's studies, [Hebrew](https://study.agri.huji.ac.il/master-info) and [English](https://en.study.agri.huji.ac.il/master-info).
* Course catalog for [research track](http://catalog.huji.ac.il/pages/wfrMaslulDetails.aspx?year=2025&faculty=8&entityId=728&chugId=728&degreeCode=72&maslulId=82840&language=en) and [non-research track](http://catalog.huji.ac.il/pages/wfrMaslulDetails.aspx?year=2025&faculty=8&entityId=728&chugId=728&degreeCode=72&maslulId=82841&language=en).

## MSc defense

* Referees must send their evaluation of the thesis to `yair.mau@mail.huji.ac.il` up to one day before the defense. See form `MSc thesis referee grading form` below.
* MSc student will prepare a presentation of 15-25 minutes.
* No food is allowed in the meeting room before and during the defense, just coffee/tea.

## Forms

<div class="alert alert-danger">
The forms below are Google Docs. Do not "Request edit access", instead copy them to your personal Google account:  
`File` then `Make a copy`.
</div>

If you need to have multiple people filling out the same form, follow this:

1. Make a copy of the form to your own google account, and after filling it out,
1. click `Share`, 
1. go to `General access`, 
1. choose `Anyone with the link`, and 
1. give them `Editor` privileges.
1. copy the link and share it with the relevant people.

* [Master’s registration request form](https://docs.google.com/document/d/1tsL4N1mGwwVAhV1mElg323rLKMldn7AsDHN3mdfPt40/edit?usp=sharing)
* [Master’s course plan — research track](https://docs.google.com/document/d/1dOBUhBwdqe5FDYGKTEbAKdZ9o77CYv2QXzlM23hG2Ag/edit?usp=sharing)
* [Thesis submission form](https://docs.google.com/document/d/1g38ETNi98lWgo5mLTkmCiN98ewAxxdhrlWCeFAU0eYA/edit?usp=sharing)
* [MSc thesis referee grading form](https://docs.google.com/document/d/1D6j2L6hgikY22bT4vYs_XWJ-XQlx5QczNwyNAm0CqOc/edit?usp=sharing)
* [MSc thesis final grade](https://docs.google.com/document/d/1yjP_MPHi_aJ4yTeFpwq2yCAW0HygX1J-oHusAEwoJN0/edit?usp=sharing)