---
title: "Recommendations"
toc: true
---

## Short stories

[They're Made out of Meat](https://www.mit.edu/people/dpolicar/writing/prose/text/thinkingMeat.html){target="_blank"}  
Mind-blowing alien-dialogue story by Terry Bisson, 1991.

[On Exactitude in Science](https://kwarc.info/teaching/TDM/Borges.pdf){target="_blank"}  
Jorge Luis Borges knocks it out of the park with a 1-paragraph story.

## Books

[The Beginning of Infinity, by David Deutsch](https://en.wikipedia.org/wiki/The_Beginning_of_Infinity){target="_blank"}  
So many good things in one book. Sure, at times Deutsch might sound like the [proverbial old physicist](https://www.smbc-comics.com/comic/2012-03-21). A foundational book.

[The World of Yesterday, by Stefan Zweig](https://en.wikipedia.org/wiki/The_World_of_Yesterday){target="_blank"}  
Excellent first-person account of Europe's societal and cultural changes, from *La Belle Époque* to WW2.

[Everything Is Tuberculosis, by John Green](https://en.wikipedia.org/wiki/Everything_Is_Tuberculosis){target="_blank"}  
Such beautiful prose! You'll start caring about something you probably never think about.

[Chaos, by James Gleick](https://en.wikipedia.org/wiki/Chaos:_Making_a_New_Science){target="_blank"}
It was probably after reading it as a teenager that I decided to study Physics.

[The Sleepwalkers: How Europe Went to War in 1914, by Christopher Clark](https://en.wikipedia.org/wiki/The_Sleepwalkers:_How_Europe_Went_to_War_in_1914){target="_blank"}  
If you like History, read it!

[Siddhartha, by Hermann Hesse](https://en.wikipedia.org/wiki/Siddhartha_(novel)){target="_blank"}  
Just beautiful.

[Debt: The First 5,000 Years, by David Graeber](https://en.wikipedia.org/wiki/Debt:_The_First_5,000_Years){target="_blank"}  
Not an easy read; it will crack your head wide open.
    
[The World Until Yesterday, by Jared Diamond](https://en.wikipedia.org/wiki/The_World_Until_Yesterday){target="_blank"}  
I think about this book a lot. About the many ways the society I live in is just a tiny local minimum in a vast landscape.

[Justice, by Michael J. Sandel](https://en.wikipedia.org/wiki/Justice:_What%27s_the_Right_Thing_to_Do%3F){target="_blank"}  
A superb introduction to Moral Philosophy

[Born a Crime, by Trevor Noah](https://en.wikipedia.org/wiki/Born_a_Crime){target="_blank"}  
When someone who has never listened to (read) an audiobook asks me where they should start, I always recommend this one. Narrated by the author.

[The Name of the Rose, by Umberto Eco](https://en.wikipedia.org/wiki/The_Name_of_the_Rose){target="_blank"}  
I just love Eco, read them all. Start here.

[Waking Up, by Sam Harris](https://en.wikipedia.org/wiki/Waking_Up:_A_Guide_to_Spirituality_Without_Religion){target="_blank"}  
What is the mind? What's consciousness? Beautiful.

[36 Arguments for the Existence of God: A Work of Fiction, by Rebecca Goldstein](https://www.jewishbookcouncil.org/book/36-arguments-for-the-existence-of-god-a-work-of-fiction){target="_blank"}  
Goldstein is a literary genius. I suppose that being Jewish would really help understanding so many of the references in this book.

[The Unfolding of Language, by Guy Deutscher](https://www.goodreads.com/book/show/262579.The_Unfolding_of_Language){target="_blank"}  
Best linguistics book ever.

[Contact, by Carl Sagan](https://en.wikipedia.org/wiki/Contact_(novel)){target="_blank"}  
Whenever I'm asked what's my favorite book, that's my answer.

[The Selfish Gene, by Richard Dawkins](https://en.wikipedia.org/wiki/The_Selfish_Gene){target="_blank"}  
I read a bunch of Dawkins when I was 16--18. This was eye opening.

[Superintelligence, by Nick Bostrom](https://en.wikipedia.org/wiki/Superintelligence:_Paths,_Dangers,_Strategies){target="_blank"}  
I didn't sleep well for three months after reading this.

[Infidel, by Ayaan Hirsi Ali](https://en.wikipedia.org/wiki/Infidel:_My_Life){target="_blank"}  
She is a true hero, champion of freedom.
